### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by ner0x652** [x64dbg/x64dbgida#2]
Hi,

what are the minimum requirements(versions) of IDAPro and x64dbg for running the plugin?

Thank you!

P.S. On x64dbg v25 and IDAPro 6.0 didn't work, IDAPro crashes.

**Comment by mrexodia** [comment]
I tested on IDA 6.8 where does it crash?

**Comment by ner0x652** [comment]
It(IDAPro) crashes at the startup.

**Comment by ner0x652** [comment]
I think it is a Python2.6 problem, from crash dump file in WinDbg:
`python26!PyFloat_FromString+0x245:
1e0c2c72 dd1c24 fstp qword ptr [esp] ss: 0002b: 0019d188=0000000000000000`

**Comment by mrexodia** [comment]
Probably that's a bug in ida then...

**Comment by mrexodia** [comment]
Can you try with Python 2.7?

**Comment by ner0x652** [comment]
Can I force IDAPro 6.0 use python2.7? How?

I think it uses an embedded Python interpreter.

**Comment by mrexodia** [comment]
Hm, it looks like the culprit is `import json` if you remove it the script (just pushed a fix for the menus) runs fine.

**Comment by mrexodia** [comment]
IDA 6.2 with Python 2.6 works without problems.

**Comment by mrexodia** [comment]
Try https://github.com/idapython/src/blob/build-1.7.2/RELEASES/idapython-1.2.0_ida5.4_py2.5_win32.zip and try deleting `chart.plw`

**Comment by mrexodia** [comment]
Sorry I mean https://github.com/idapython/src/blob/build-1.7.2/RELEASES/idapython-1.4.3_ida6.0_py2.7_win32.zip
