### ISSUE TITLE
X64dbg 27.11 does not import database exported from IDA 6.85

### ISSUE THREAD

**Issue by kornos** [x64dbg/x64dbgida#3]
Hello Mr. Exodia

I try to import names from IDA 6.85 in X64dbg ver 27.11, but it doesn't work.

Exported database looks ok 👍 
 {
   "text": "__tmainCRTStartup", 
   "manual": false, 
   "module": "PilotEdit.exe", 
   "address": "0x9B8D0"
  }, 

In IDA it shows:
.text:000000014009BAA8                 public start
.text:000000014009BAA8 start           proc near               ; DATA XREF: HEADER:0000000140000120o
.text:000000014009BAA8                                         ; .pdata:00000001409ACB24o ...
.text:000000014009BAA8                 sub     rsp, 28h
.text:000000014009BAAC                 call    __security_init_cookie
.text:000000014009BAB1                 add     rsp, 28h
.text:000000014009BAB5                 jmp     __tmainCRTStartup
.text:000000014009BAB5 start           endp

Same code snippet In X64DBG it shows:

000000014009BAA8 | 48 83 EC 28              | sub rsp,28                              |
000000014009BAAC | E8 E3 7F 00 00           | call pilotedit.1400A3A94                |
000000014009BAB1 | 48 83 C4 28              | add rsp,28                              |
000000014009BAB5 | E9 16 FE FF FF           | jmp pilotedit.14009B8D0                 |

I expected __tmainCRTStartup to appear in X64DBG , but it doesn't.
Where is the problem ?

Thanks very much

**Comment by mrexodia** [comment]
Could you list all labels (toolbar on the top of x64dbg) I have a feeling
that IDA reported the wrong image base...

**Comment by kornos** [comment]
It's here:

https://drive.google.com/open?id=0B1gPVgT74q9LNXhfdWIzdzVnczQ

**Comment by mrexodia** [comment]
I cannot really make much sense of what's going on here. Could you post the last line of the infobox when highlighting the address that should have `__tmainCRTStartup`?

**Comment by kornos** [comment]
Excuse me , where is located the "infobox" (what program/menu - ida or x64dbg)?

As far as I can see in IDA and X64 dbg , the adress of __tmainCRTstartup is: 00014009B8D0
This adress also appears in X64dbg in the right place.

I can upload whole .ida file , if it's easier to track this.

**Comment by mrexodia** [comment]
Yeah that might be useful. The info box is located under the disassembly.
I'm not looking for the virtual address but the address relative to the
image base.

**Comment by kornos** [comment]
.ida file link: https://drive.google.com/open?id=0B1gPVgT74q9Lai1jS09VZk13X2s

**Comment by kornos** [comment]
ah , you mean infobox is in X64dbg?

When I highlight the adress 14009B8D0(where __tmainCRTstartup begins) , in that small box under dissasembly in X64dbg it written:

qword [rsp+10]=[000000000013FF68]=0
rbx=<pilotedit.EntryPoint>
.text:000000014009B8D0 pilotedit.exe:$9B8D0 #9ACD0

**Comment by kornos** [comment]
The program I was analyzing is PilotEdit 10.0.0 64bit  http://www.pilotedit.com/
In case there's anything else you want me to do , please ask.

Did you find the source of the problem?

Thanks

**Comment by Nukem9** [comment]
![image](https://cloud.githubusercontent.com/assets/4228359/20735366/9c122192-b66d-11e6-83ea-30a1c5a67ed1.png)
----
![image](https://cloud.githubusercontent.com/assets/4228359/20735287/12e1aab4-b66d-11e6-8a19-1ff317e2b3e6.png)
----
![image](https://cloud.githubusercontent.com/assets/4228359/20735292/1cd17eb4-b66d-11e6-8d2d-6a3c81fc605c.png)
----
![image](https://cloud.githubusercontent.com/assets/4228359/20735294/2213e1e6-b66d-11e6-91e5-9b441a3a8974.png)
----

It's case sensitive @mrexodia.
`"module": "PilotEdit.exe",` does not work.
`"module": "pilotedit.exe",` works.

**Comment by kornos** [comment]
Mr Exodia , I confirm it works it's about case sensitive exe filename.
It means that X64dbg should be patched to lowercase the filenames?

Nukem9++ , thank very much ;-)

**Comment by mrexodia** [comment]
Oh yes I will update both x64dbg and the IDA plugin. In x64dbg everything
is already lower case but I didn't consider wrong data coming from other
sources 😀
